export const jobs = [
  {
    id: 1,
    title: "Software Developer",
    company: "TechInnovate",
    location: "San Francisco, CA",
    salary: "$90,000 - $120,000",
    requirements: "JavaScript, React, Node.js",
    description: "Join our team developing cutting-edge web applications using modern technologies. You'll be part of an agile team building responsive and scalable applications for our diverse client base. Daily tasks include front-end development with React, back-end API development with Node.js, and collaborating with UX/UI designers to implement user-friendly interfaces.",
    experienceLevel: "3-5 years",
    languageRequirement: "intermediate",
    availability: "full-time",
    industry: "technology",
    benefits: "Health insurance, 401(k) matching, flexible work schedule, professional development budget",
    applicationUrl: "https://www.techinnovate.example.com/careers/software-developer"
  },
  {
    id: 2,
    title: "Nurse Assistant",
    company: "MediCare Hospital",
    location: "New York, NY",
    salary: "$45,000 - $55,000",
    requirements: "Certified Nursing Assistant, CPR certification",
    description: "Assist nurses in providing patient care in a fast-paced hospital environment. Responsibilities include taking vital signs, helping patients with daily activities, monitoring and recording patient conditions, and maintaining clean and safe patient areas. You'll be an essential part of our healthcare team, providing compassionate care to patients with diverse needs.",
    experienceLevel: "1-3 years",
    languageRequirement: "intermediate",
    availability: "full-time",
    industry: "healthcare",
    benefits: "Health and dental insurance, retirement plan, paid time off, tuition reimbursement for further certifications",
    applicationUrl: "https://www.medicare-hospital.example.com/jobs/nurse-assistant"
  },
  {
    id: 3,
    title: "Hotel Receptionist",
    company: "Grand Hotel",
    location: "Miami, FL",
    salary: "$35,000 - $40,000",
    requirements: "Customer service experience, basic computer skills",
    description: "Greet and assist hotel guests, manage reservations, and handle inquiries. You'll be the first point of contact for our guests, providing exceptional customer service and ensuring a pleasant stay. Responsibilities include check-in/check-out procedures, answering phone calls, processing payments, and resolving guest concerns. Knowledge of multiple languages is a plus in our diverse tourist location.",
    experienceLevel: "0-1 year",
    languageRequirement: "beginner",
    availability: "full-time",
    industry: "hospitality",
    benefits: "Discounted hotel stays, meal allowance, health insurance, potential for advancement",
    applicationUrl: "https://www.grandhotel-miami.example.com/careers"
  },
  {
    id: 4,
    title: "Warehouse Associate",
    company: "Global Logistics",
    location: "Chicago, IL",
    salary: "$32,000 - $38,000",
    requirements: "Ability to lift up to 50 lbs, basic English",
    description: "Responsible for receiving, storing, and shipping products within our warehouse facility. Key duties include loading and unloading shipments, picking and packing orders, operating forklifts (training provided), maintaining inventory accuracy, and ensuring a clean and safe work environment. This position offers regular hours with occasional overtime opportunities during busy seasons.",
    experienceLevel: "no experience",
    languageRequirement: "beginner",
    availability: "full-time",
    industry: "manufacturing",
    benefits: "Health insurance, paid holidays, employee discount program, opportunities for advancement",
    applicationUrl: "https://www.globallogistics.example.com/apply/warehouse"
  },
  {
    id: 5,
    title: "Part-time Cashier",
    company: "SuperMart",
    location: "Los Angeles, CA",
    salary: "$15 - $18 per hour",
    requirements: "Basic math skills, friendly attitude",
    description: "Operate cash registers, assist customers, and maintain a clean checkout area. This position involves processing transactions, handling cash and card payments, bagging items, and providing excellent customer service. You'll also help with stocking shelves, organizing displays, and assisting with store promotions. Flexible scheduling available, perfect for students or those seeking supplementary income.",
    experienceLevel: "no experience",
    languageRequirement: "beginner",
    availability: "part-time",
    industry: "retail",
    benefits: "Employee discount, flexible scheduling, paid training, growth opportunities",
    applicationUrl: "https://www.supermart.example.com/jobs"
  },
  {
    id: 6,
    title: "Construction Helper",
    company: "BuildRight Construction",
    location: "Houston, TX",
    salary: "$20 - $25 per hour",
    requirements: "Physical stamina, basic construction knowledge",
    description: "Assist skilled workers on construction sites by moving materials and performing basic tasks. You'll help with site preparation, loading and unloading building materials, assisting carpenters and other tradespeople, cleaning and maintaining tools, and ensuring site safety. This position offers an excellent opportunity to learn construction trades and potentially advance to more skilled positions with training and experience.",
    experienceLevel: "no experience",
    languageRequirement: "beginner",
    availability: "full-time",
    industry: "construction",
    benefits: "Competitive wages, potential for overtime, on-the-job training, safety equipment provided",
    applicationUrl: "https://www.buildright.example.com/employment"
  },
  {
    id: 7,
    title: "ESL Teacher Assistant",
    company: "Language Learning Center",
    location: "Boston, MA",
    salary: "$40,000 - $45,000",
    requirements: "Bilingual (Spanish/English preferred), experience working with students",
    description: "Support ESL teachers in classroom instruction and help students improve their English skills. You'll assist with lesson preparation, provide one-on-one support to students, help with classroom management, facilitate small group activities, and assist with student assessment. This role is ideal for those passionate about education and helping immigrants succeed through language acquisition. Experience with diverse cultural backgrounds is highly valued.",
    experienceLevel: "1-3 years",
    languageRequirement: "advanced",
    availability: "full-time",
    industry: "education",
    benefits: "Health insurance, paid time off, summer breaks, professional development opportunities",
    applicationUrl: "https://www.languagelearningcenter.example.com/careers/teacher-assistant"
  },
  {
    id: 8,
    title: "IT Support Specialist",
    company: "Global Tech Solutions",
    location: "Austin, TX",
    salary: "$55,000 - $65,000",
    requirements: "Technical troubleshooting skills, customer service experience",
    description: "Provide technical support to employees and resolve hardware/software issues. Your responsibilities will include diagnosing and solving computer problems, setting up workstations for new employees, maintaining network systems, installing and configuring software, and documenting technical solutions. You'll be part of a collaborative IT team supporting a growing organization with diverse technology needs.",
    experienceLevel: "1-3 years",
    languageRequirement: "intermediate",
    availability: "full-time",
    industry: "technology",
    benefits: "Competitive salary, comprehensive benefits package, professional development budget, flexible work arrangements",
    applicationUrl: "https://www.globaltechsolutions.example.com/careers/it-support"
  },
  {
    id: 9,
    title: "Home Health Aide",
    company: "Caring Hands Health Services",
    location: "Phoenix, AZ",
    salary: "$30,000 - $35,000",
    requirements: "Home Health Aide certification, compassionate nature",
    description: "Provide personal care and support services to patients in their homes. Your duties will include assisting clients with daily activities like bathing, dressing, and grooming; preparing meals according to dietary restrictions; light housekeeping; medication reminders; and monitoring and recording client conditions. This rewarding position allows you to make a meaningful difference in the lives of those who need assistance while maintaining their independence.",
    experienceLevel: "0-1 year",
    languageRequirement: "beginner",
    availability: "part-time",
    industry: "healthcare",
    benefits: "Flexible scheduling, mileage reimbursement, paid training, career advancement opportunities",
    applicationUrl: "https://www.caringhands.example.com/join-our-team"
  },
  {
    id: 10,
    title: "Kitchen Staff",
    company: "Delicious Bites Restaurant",
    location: "Denver, CO",
    salary: "$16 - $18 per hour",
    requirements: "Food handling experience, ability to work in a fast-paced environment",
    description: "Prepare ingredients, assist chefs, and maintain cleanliness in the kitchen. Your responsibilities will include washing, peeling, and cutting food items; preparing simple dishes following recipes; plating and garnishing meals; operating kitchen equipment; maintaining inventory; and ensuring health and safety standards are met. Previous kitchen experience is helpful but not required - we provide training for motivated individuals interested in the culinary field.",
    experienceLevel: "0-1 year",
    languageRequirement: "beginner",
    availability: "part-time",
    industry: "hospitality",
    benefits: "Free meals during shifts, flexible scheduling, potential for tips, opportunity to learn culinary skills",
    applicationUrl: "https://www.deliciousbites.example.com/jobs"
  },
  {
    id: 11,
    title: "Retail Associate",
    company: "Fashion Forward",
    location: "Seattle, WA",
    salary: "$15 - $17 per hour",
    requirements: "Customer service skills, sales experience a plus",
    description: "Assist customers, maintain store appearance, and process sales transactions. In this role, you'll help customers find products, make recommendations based on their preferences, operate the point-of-sale system, arrange merchandise displays, restock inventory, and ensure the sales floor is clean and organized. You'll be part of a dynamic team in a fashion-forward environment where your input on trends and customer preferences is valued.",
    experienceLevel: "0-1 year",
    languageRequirement: "beginner",
    availability: "part-time",
    industry: "retail",
    benefits: "Employee discount (40% off merchandise), flexible scheduling, commission opportunities, advancement potential",
    applicationUrl: "https://www.fashionforward.example.com/apply"
  },
  {
    id: 12,
    title: "Assembly Line Worker",
    company: "Auto Parts Manufacturing",
    location: "Detroit, MI",
    salary: "$35,000 - $40,000",
    requirements: "Manual dexterity, ability to stand for long periods",
    description: "Assemble components according to specifications in a manufacturing environment. The role involves following detailed assembly instructions, using hand and power tools to assemble auto parts, conducting quality checks, meeting daily production targets, and following safety protocols. We provide complete training on all procedures, and there are opportunities for advancement to team leader positions for dedicated employees who demonstrate reliability and attention to detail.",
    experienceLevel: "no experience",
    languageRequirement: "beginner",
    availability: "full-time",
    industry: "manufacturing",
    benefits: "Health insurance, retirement plan with company match, paid vacation, employee assistance program",
    applicationUrl: "https://www.autopartsmfg.example.com/employment-opportunities"
  }
];
